pipeline {
    agent any

    environment {
        DOCKER_DIR = '/var/lib/jenkins/workspace/DevOps/microservices'
        ECR_REPO = '471112848311.dkr.ecr.us-east-1.amazonaws.com/devops_final-repository'
        AWS_REGION = 'us-east-1'
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    parameters {
        choice(name: 'MICROSERVICE', choices: ['portfolio-service', 'gallery-service'], description: 'Microservice to deploy')
        choice(name: 'BRANCH_NAME', choices: ['dev', 'uat', 'prod'], description: 'Branch to deploy')
        string(name: 'GIT_TAG', defaultValue: 'latest', description: 'Git tag for deployment')
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        userRemoteConfigs: [[url: 'https://github.com/rotanaapp/final_devops_II.git']],
                        branches: [[name: "*/${params.BRANCH_NAME}"]],
                        doGenerateSubmoduleConfigurations: false,
                        submoduleCfg: [],
                        extensions: []
                    ])
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    def appName = params.MICROSERVICE
                    
                    // Build Docker image
                    sh "docker build -t ${ECR_REPO}:${env.BUILD_NUMBER} -f ${env.DOCKER_DIR}/${appName}/Dockerfile ./${appName}"
                    
                    // Log in to ECR
                    // sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}"
                    sh "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112848311.dkr.ecr.us-east-1.amazonaws.com"
                    // Push Docker image to ECR
                    sh "docker push ${ECR_REPO}:${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Success"
                //     def appName = params.MICROSERVICE
                //     def terraformDir = "${appName}/terraform/"
                //     dir(terraformDir) {
                //         sh "terraform init"
                //         sh "terraform apply -var=\"image=${ECR_REPO}/${appName}:${env.BUILD_NUMBER}\" -auto-approve"
                //     }
                }
            }
        }
    }
}
