pipeline {
    agent any

    environment {
        DOCKER_DIR = '/var/lib/jenkins/workspace/DevOps'
        ECR_REPO = '471112848311.dkr.ecr.us-east-1.amazonaws.com/devops_final-repository'
        AWS_REGION = 'us-east-1'
    }

    parameters {
        choice(name: 'MICROSERVICE', choices: ['portfolio-service', 'gallery-service'], description: 'Microservice to deploy')
        choice(name: 'BRANCH_NAME', choices: ['dev', 'uat', 'prod'], description: 'Branch to deploy')
        string(name: 'GIT_TAG', defaultValue: 'latest', description: 'Git tag for deployment')
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        userRemoteConfigs: [[url: 'https://github.com/rotanaapp/final_devops_II.git']],
                        branches: [[name: "*/${params.BRANCH_NAME}"]],
                        doGenerateSubmoduleConfigurations: false,
                        submoduleCfg: [],
                        extensions: []
                    ])
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                echo "Success"
                echo "${DOCKER_DIR}/${appName}/"
                // script {
                //     def appName = params.MICROSERVICE
                //     // sh "docker build -t ${ECR_REPO}/${appName}:${env.BUILD_NUMBER} ./${appName}/"
                //     sh "docker build -t ${ECR_REPO}:${env.BUILD_NUMBER} -f ${DOCKER_DIR}/${appName}/ ./${appName}/"
                //     // sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}"
                //     sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin 471112848311.dkr.ecr.us-east-1.amazonaws.com"
                //     sh "docker push ${ECR_REPO}:${env.BUILD_NUMBER}"
                // }
                // script {
                //     def appName = params.MICROSERVICE
                //     def terraformDir = "${appName}/"
                //     dir(terraformDir) {
                //         sh "docker build -t ${ECR_REPO}:${env.BUILD_NUMBER} ./${appName}/"
                //         sh "terraform apply -var=\"image=${ECR_REPO}/${appName}:${env.BUILD_NUMBER}\" -auto-approve"
                //     }
                // }
            }
        }

        stage('Deploy') {
            steps {
                echo "Success"

                // script {
                //     def appName = params.MICROSERVICE
                //     def terraformDir = "${appName}/terraform/"
                //     dir(terraformDir) {
                //         sh "terraform init"
                //         sh "terraform apply -var=\"image=${ECR_REPO}/${appName}:${env.BUILD_NUMBER}\" -auto-approve"
                //     }
                // }
            }
        }
    }
}
